# SPDX-FileCopyrightText: 2026  IMAGIN sp. z o.o.
# SPDX-FileContributor: Marcin Engelmann <mengelmann@octivi.com>
# SPDX-License-Identifier: MIT
printWidth: 80
tabWidth: 2
useTabs: false
overrides:
  - files: "*.md"
    options:
      printWidth: 100
      proseWrap: always
  # Prettier messes up the formatting of frontmatter in SKILL.md
  - files: "*/SKILL.md"
    options:
      proseWrap: preserve
